name: Build
on:
  schedule:
    - cron: 0 4 * * *

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      runner_image:
        description: "Runner Image"
        required: true
        type: string
        default: "ubuntu-latest"

      debug_with_ssh:
        description: "Debug with SSH"
        type: boolean
        default: false

      upload_to_server:
        description: "Upload firmware to file server"
        type: boolean
        default: false

      clean_build:
        description: "Skip use cache and clean cache"
        type: boolean
        default: false

      build_openwrt_x86_64:
        description: "Build openwrt-x86_64"
        type: boolean
        default: true

      build_openwrt_armsr_armv8:
        description: "Build openwrt-armsr-armv8"
        type: boolean
        default: true

jobs:
  openwrt-x86_64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_openwrt_x86_64 }}
    runs-on: ${{ github.event.inputs.runner_image || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Prepare Environment and Save Build Configs
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash prenv.sh
          cp openwrt/x86_64 /tmp/.config

      - name: Free up disk space on Ubuntu runners
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repo
        uses: actions/checkout@main
        with:
          repository: openwrt/openwrt
          fetch-depth: 0
          ref: main

      - name: Cache
        uses: stupidloud/cachewrtbuild@main
        with:
          ccache: true
          mixkey: "openwrt_x86_64"
          skip: ${{ ! github.event.inputs.clean_build || true }}
          clean: ${{ github.event.inputs.clean_build || false }}

      - name: Download and Load custom configuration
        run: |
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config
          rm -rf package/openwrt-passwall2 package/openwrt-passwall-packages
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall2.git package/openwrt-passwall2
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall-packages.git package/openwrt-passwall-packages
          ./scripts/feeds update -a && ./scripts/feeds install -a
          cp /tmp/.config .config
          make defconfig clean

      - name: Try to Build When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=99
          sudo df -h

      - name: Prepare Image Artifact
        if: success()
        run: |
          mkdir -p images
          cp -r bin/targets/*/*/*.gz images/
          cp -r bin/targets/*/*/sha256sums images/

      - name: Upload Artifact Images
        if: success()
        uses: actions/upload-artifact@main
        with:
          compression-level: 9
          include-hidden-files: true
          name: openwrt_x86_64-images
          path: images

      - name: Prepare Packages Artifact
        if: success()
        run: |
          mkdir -p pkgs
          cp -r bin/targets/*/*/packages pkgs/

      - name: Upload Artifact Packages
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: openwrt_x86_64-packages
          path: pkgs

      - name: Upload firmware to Download Station
        if: ${{ github.event.inputs.upload_to_server || false }} && success()
        run: |
          cd bin/targets/*/*
          zip -r -o -q -9 file.zip . -i *.gz
          [[ -f file.zip ]] && curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/openwrt/x86_64" -F "file=@file.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}

  openwrt-armsr-armv8:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build_openwrt_armsr_armv8 }}
    runs-on: ${{ github.event.inputs.runner_image || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Prepare Environment and Save Build Configs
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash prenv.sh
          cp openwrt/config-armsr-armv8 /tmp/.config

      - name: Free up disk space on Ubuntu runners
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repo
        uses: actions/checkout@main
        with:
          repository: openwrt/openwrt
          fetch-depth: 0
          ref: main

      - name: Cache
        uses: stupidloud/cachewrtbuild@main
        with:
          ccache: true
          mixkey: "openwrt_armsr_armv8"
          skip: ${{ ! github.event.inputs.clean_build || true }}
          clean: ${{ github.event.inputs.clean_build || false }}

      - name: Download and Load custom configuration
        run: |
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config
          rm -rf package/openwrt-passwall2 package/openwrt-passwall-packages
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall2.git package/openwrt-passwall2
          git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall-packages.git package/openwrt-passwall-packages
          ./scripts/feeds update -a && ./scripts/feeds install -a
          cp /tmp/.config .config
          make defconfig clean

      - name: Try to Build When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=99
          sudo df -h

      - name: Prepare Image Artifact
        if: success()
        run: |
          mkdir -p images
          cp -r bin/targets/*/*/*.gz images/
          cp -r bin/targets/*/*/sha256sums images/

      - name: Upload Artifact Images
        if: success()
        uses: actions/upload-artifact@main
        with:
          compression-level: 9
          include-hidden-files: true
          name: openwrt_armsr_armv8-images
          path: images

      - name: Prepare Packages Artifact
        if: success()
        run: |
          mkdir -p pkgs
          cp -r bin/targets/*/*/packages pkgs/

      - name: Upload Artifact Packages
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: openwrt_armsr_armv8-packages
          path: pkgs

      - name: Upload firmware to Download Station
        if: ${{ github.event.inputs.upload_to_server || false }} && success()
        run: |
          cd bin/targets/*/*
          zip -r -o -q -9 file.zip . -i *.gz
          [[ -f file.zip ]] && curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/openwrt/armsr_armv8" -F "file=@file.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
          delete_workflow_pattern: build.yml