name: Build-lede
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0/6 * * *
jobs:
  x86:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/main/immortalwrt/prenv.sh)
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: coolsnowwolf/lede
          fetch-depth: 0
          ref: master
      - name: Cache
        uses: klever1988/cachewrtbuild@main
        with:
          ccache: true
          toolchain: true
          skip: true
          clean: false
      - name: Download and Load custom configuration
        run: |
          curl -fsSL https://raw.githubusercontent.com/1orz/My-action/main/lede/config-x86-64 >.config
          echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config; make defconfig
      - name: Try to Build When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo -e "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=sc
          make package/feeds/luci/luci-base/compile -j1 V=99
          make -j$(nproc) || make -j1 V=sc
          sudo df -h
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: x86_64
          path: bin/targets/*/*
      # - name: Upload firmware to Download Station
      #   if: success()
      #   run: |
      #     cd bin/targets/*/*
      #     zip -r -o -q -9 x86_64.zip . -i *.gz
      #     curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/immortalwrt/x86_64" -F "file=@x86_64.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 90
          keep_minimum_runs: 1
